### ISSUE TITLE
замечания

### ISSUE THREAD

**Issue by demist** [MVCionOld/Tsiolization#1]
+ не увидел схемы архитектуры
+ почему бы, например, не сделать этап создания фракций (= фабрик), через прототип?
Правильно ли я понимаю, что игроков может быть много?

**Comment by MVCionOld** [comment]
Подразумевалось, что от 1 до 4 игроков, поэтому без прототипа

**Comment by demist** [comment]
ок, принято

жду схему архитектуры

**Comment by demist** [comment]
засчитано
